# Generated by Django 2.0.3 on 2018-03-09 23:43

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='photo',
            field=models.ImageField(upload_to=blog.models.renommage, verbose_name='Document'),
        ),
    ]
