# Generated by Django 2.0.3 on 2018-03-09 23:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MiniURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longURL', models.URLField(unique=True)),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='URL à réduire')),
                ('pseudo_auteur', models.CharField(max_length=42, null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création')),
                ('nb_access', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'mini_url',
                'ordering': ['date'],
            },
        ),
    ]
