# Generated by Django 2.0.3 on 2018-03-10 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_url', '0002_auto_20180309_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miniurl',
            name='pseudo_auteur',
            field=models.CharField(blank=True, max_length=42, null=True),
        ),
    ]
