# Generated by Django 2.0.3 on 2018-03-10 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mini_url', '0003_auto_20180310_0033'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='miniurl',
            options={'verbose_name': 'Mini URL', 'verbose_name_plural': 'Minis URL'},
        ),
    ]
